---
- hosts: all
  become: yes
  tasks: 
  - name: Install prerequisites
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: latest
      update_cache: true

  - name: Add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  - name: Install docker and it's dependencies
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Start and enable docker daemon
    service:
      name: docker
      state: started
      enabled: yes

  - name: adding existing user to group docker
    user:
      name: "{{ ansible_user }}"
      groups: docker


  - name: Install Docker-compose
    shell: | 
      curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
      chmod +x /usr/local/bin/docker-compose
      ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose