---
- hosts: all
  tasks: 
  - name: Install prerequisites
    become: yes
    apt:
      pkg:
        - zsh
        - fonts-powerline
        - fzf
      state: latest
      update_cache: true

  - name: Download the install script
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /home/{{ ansible_user }}/install.sh

  - name: Changing permission of script
    file: dest=/home/{{ ansible_user }}/install.sh mode=a+x

  - name: Instal ohmyzsh
    shell: yes "" | NO_INTERACTIVE=true sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

  - name: Remove script
    ansible.builtin.file:
      path: /home/{{ ansible_user }}/install.sh
      state: absent   

  - name: Change user shell to zsh 
    become: yes
    user:
      name: "{{ ansible_user }}"
      shell: /bin/zsh
    
  - name: Install autosuggestions plugin
    shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    
  - name: Download the install script
    get_url:
      url: https://raw.githubusercontent.com/azeljkovic/shell_linux_setup/main/.zshrc
      dest: /home/{{ ansible_user }}/.zshrc
